### ISSUE TITLE
Error when trying to use skrape.it

### ISSUE THREAD

**Issue by noloman** [skrapeit/skrape.it#101] opened 2020-08-22 11:57 UTC
**describe what you want to archive**
I want to start using skrape.it but I'm running into the following error after adding the dependency to my gradle file `implementation("it.skrape:skrapeit-core:1.0.0-alpha6")`

```Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform skrapeit-core-1.0.0-alpha6.jar (it.skrape:skrapeit-core:1.0.0-alpha6) to match attributes {artifactType=android-dex, dexing-enable-desugaring=true, dexing-incremental-transform=false, dexing-is-debuggable=true, dexing-min-sdk=29, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: /Users/manu/.gradle/caches/transforms-2/files-2.1/b4b9b9355700eff7cbfa9b7478e92c84/jetified-skrapeit-core-1.0.0-alpha6.jar.
         > Error while dexing.
```

**Comment by christian-draeger** [comment] 2020-08-23 18:08
see https://github.com/skrapeit/skrape.it/issues/93#issuecomment-678804992 

because it seems to be a duplicate of #93 i'm closing this issue

**Closed** 2020-08-23 18:07 UTC
Labels: question
