### ISSUE TITLE
[BUG] Unable to crawling the mvnrepository site

### ISSUE THREAD

**Issue by RinOrz** [skrapeit/skrape.it#151] opened 2021-06-28 13:57 UTC
Crawling this website in **skrape.it** will get the wrong HTML, directly in `jsoup` will get _403_,  but if via `okhttp`, everything is normal, can this be solved?

My current solution is:
```kotlin
skrape(OkHttpFetcher) {
  request { url = "https://mvnrepository.com/artifact/kotlin" }
  println(scrape().responseBody)
}

object OkHttpFetcher : NonBlockingFetcher<Request> {
  override val requestBuilder: Request get() = Request()

  @Suppress("BlockingMethodInNonBlockingContext")
  override suspend fun fetch(request: Request): Result = OkHttpClient().newCall(
    okhttp3.Request.Builder()
      .url(request.url)
      .build()
  ).execute().let {
    val body = it.body!!
    Result(
      responseBody = body.string(),
      responseStatus = Result.Status(it.code, it.message),
      contentType = body.contentType()?.toString()?.replace(" ", ""),
      headers = it.headers.toMap(),
      cookies = emptyList(),
      baseUri = it.request.url.toString()
    )
  }
}
```

**Comment by christian-draeger** [comment] 2021-06-28 20:38
hey
it is simply because you are building a request object but then you are not call ing the correct function to run the scraper :)
tyou can try something like this:

```kotlin
fun main() {
    val responseBody = skrape(HttpFetcher) {
        request {
            url = "https://mvnrepository.com/artifact/kotlin"
        }
        extract { // <--- if you call extract or expect the request object will be taken and the scrape function of the passed Scraper will be executed. furthermore the result object will be available inside of the lambda function
            responseBody
        }
    }

    println(responseBody)
}
```

simular to what is documented in the README.md --> https://github.com/skrapeit/skrape.it#testing-html-responses

**Comment by RinOrz** [comment] 2021-06-29 03:45
@christian-draeger No, this is the same error in response, you can compare the HTML of the web page by responding, the content is wrong.

**Comment by RinOrz** [comment] 2021-06-29 03:50
Error response:
![image](https://user-images.githubusercontent.com/58068445/123734626-40639f80-d8d0-11eb-8113-e82750cd6647.png)

Correct response:
![image](https://user-images.githubusercontent.com/58068445/123734559-2924b200-d8d0-11eb-9705-e712bdd43a6b.png)

**Comment by christian-draeger** [comment] 2021-06-29 04:49
Ok now I get it :)
Looks like mvnrepository is trying to block crawlers by adding a captcha to their site.

My first guess would be that you could try to add a user-agent header to the request to "hide" that request hasn't been made by a browser.

To do so you can add user Agent paranter to the request.

```kotlin
const val CHROME_UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36" 

skrape(HttpFetcher) {
request {
url = "your.url"
userAgent = CHROME_UA
} 
extract {...} 
}
```

Sorry for bad code example formatting. I'm currently answering from my phone 😅

**Comment by RinOrz** [comment] 2021-06-29 06:18
@christian-draeger Yes, I tried this, but I regret that it doesn't work. I suspect this is the problem of the [apache engine](https://ktor.io/docs/http-client-engines.html#apache), because when I use `ktor` to visit it, it reports 403, but if I use [okhttp engine](https://ktor.io/docs/http-client-engines.html#okhttp), the response content is correct. 

Maybe you can help me figure out this problem? I am grateful 🙂 . Otherwise, `skrape.it` may should add an okhttp engine extension

**Comment by christian-draeger** [comment] 2021-06-29 08:53
Intressting would be how the requests made with apache-http (HttpFetcher) differ from the ones made with okhttp.
I mean in the end it's all just a standardized http request but it seams that okhttp uses some defaults that will lead to the behavior that mvnrepository.org's server will not detect this calls as a "bot".

We could try to send a request with both HttpFetcher and your fetcher implementation with okhttp to
https://httpbin.org/anything

Httpbin will just return the complete http request. therewith we could compare what is different between the fetchers

**Comment by RinOrz** [comment] 2021-06-29 12:46
@christian-draeger for okhttp:
```json
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Charset": "UTF-8", 
    "Host": "httpbin.org", 
    "User-Agent": "Mozilla/5.0 skrape.it", 
    "X-Amzn-Trace-Id": "Root=1-60db15d7-4389581030369c1b24e77689"
  }, 
  "json": null, 
  "method": "GET", 
  "origin": "120.84.9.222", 
  "url": "http://httpbin.org/anything"
}
```

**Comment by christian-draeger** [comment] 2021-06-29 13:34
Looks to be the exact same as the apache-http call to me 🤔
Technically it makes absolutely no sense that this settings work and the other one not 😅

**Comment by christian-draeger** [comment] 2021-06-29 21:18
since this is really specific to the bot detection of the target website you want to scrape i think i will close this issue.
from what i could investigate it is not a bug in the library and you have a workaround.

**Closed by christian-draeger** 2021-06-29 21:18 UTC
Labels: bug
