### ISSUE TITLE
[BUG] Android Studio Project crashes after adding library dependency

### ISSUE THREAD

**Issue by javiereugenio** [skrapeit/skrape.it#93] opened 2020-05-19 05:29 UTC
Hi!
Im trying to use the library in an Android project. 
As suggested here https://github.com/skrapeit/skrape.it/issues/89 I added this to my build.gradle
to avoid having problems with the methods containing space in its names and so.

```
repositories {
    maven { url "https://jitpack.io" }
}
dependencies {
      testImplementation("com.github.skrapeit:skrape.it:master-SNAPSHOT")
}
```
And I was able to run this Unit Test successfully

```
import it.skrape.core.htmlDocument
import it.skrape.matchers.toBe
import it.skrape.matchers.toContain
import it.skrape.selects.html5.h1
import it.skrape.selects.html5.p
import org.junit.Test

import org.junit.Assert.*

/**
 * Example local unit test, which will execute on the development machine (host).
 *
 * See [testing documentation](http://d.android.com/tools/testing).
 */
class ExampleUnitTest {

    @Test
    internal fun `can read and return html from String`() {
        htmlDocument(
            """
        <html>
            <body>
                <h1>welcome</h1>
                <div>
                    <p>first p-element</p>
                    <p class="foo">some p-element</p>
                    <p class="foo">last p-element</p>
                </div>
            </body>
        </html>"""
        ) {

            h1 {
                findFirst {
                    text toBe "welcome"
                }
            }
            p {
                withClass = "foo"
                findFirst {
                    text toBe "some p-element"
                    className toBe "foo"
                }
            }
            p {
                findAll {
                    this@htmlDocument.text toContain "p-element"
                }
                findLast {
                    text toBe "last p-element"
                }
            }

        }
    }
}

```

![image](https://user-images.githubusercontent.com/31039354/82285944-998d9f80-996a-11ea-9132-804e5abd7a5f.png)

No problem so far, I guess because the Unit Tests run inside JVM.

After that I tried to add the dependency to use it from my Android Project adding this to my build.gradle

`implementation("com.github.skrapeit:skrape.it:master-SNAPSHOT")`

And received this error: 

**More than one file was found with OS independent path 'META-INF/DEPENDENCIES'**

After a little google search I found [this](https://stackoverflow.com/questions/57832937/how-to-fix-more-than-one-file-was-found-with-os-independent-path-meta-inf-depe) to be the possible solution, so I added this to my build.gradle

```
android {
    packagingOptions {
        pickFirst "META-INF/DEPENDENCIES"
    }
}
```
After adding that Im gettin more errors, so I think this might not be the solution 
Here is the StackTrace when I try to run the app

```
2020-05-19 01:26:30.841 14644-14644/? I/webscrappertes: Late-enabling -Xcheck:jni
2020-05-19 01:26:30.879 14644-14644/? E/webscrappertes: Unknown bits set in runtime_flags: 0x8000
2020-05-19 01:26:31.299 14644-14644/? W/webscrappertes: Bad encoded_array value: Failure to verify dex file '/data/app/cu.neosoft.webscrappertest-hy3VhMUfmFw2eV1pLwg5LQ==/base.apk': Bad encoded_value method type size 7
2020-05-19 01:26:31.306 14644-14644/? E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/cu.neosoft.webscrappertest-hy3VhMUfmFw2eV1pLwg5LQ==/base.apk"],nativeLibraryDirectories=[/data/app/cu.neosoft.webscrappertest-hy3VhMUfmFw2eV1pLwg5LQ==/lib/arm64, /system/lib64, /vendor/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:256)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:855)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:950)
        at android.app.LoadedApk.getResources(LoadedApk.java:1188)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2462)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2454)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6353)
        at android.app.ActivityThread.access$1300(ActivityThread.java:220)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/cu.neosoft.webscrappertest-hy3VhMUfmFw2eV1pLwg5LQ==/base.apk because: Bad encoded_array value: Failure to verify dex file '/data/app/cu.neosoft.webscrappertest-hy3VhMUfmFw2eV1pLwg5LQ==/base.apk': Bad encoded_value method type size 7
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:365)
        at dalvik.system.DexFile.<init>(DexFile.java:107)
        at dalvik.system.DexFile.<init>(DexFile.java:80)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:444)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:403)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:126)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:101)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:74)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:87)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:116)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:114)
        at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:60)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:851)
        		... 13 more
2020-05-19 01:26:31.330 14644-14644/? I/Perf: Connecting to perf service.
2020-05-19 01:26:31.342 14644-14679/? E/Perf: Fail to get file list cu.neosoft.webscrappertest
2020-05-19 01:26:31.342 14644-14679/? E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2020-05-19 01:26:31.342 14644-14679/? E/Perf: Fail to get file list cu.neosoft.webscrappertest
2020-05-19 01:26:31.343 14644-14679/? E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2020-05-19 01:26:31.396 14644-14644/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-05-19 01:26:31.400 14644-14644/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cu.neosoft.webscrappertest, PID: 14644
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{cu.neosoft.webscrappertest/cu.neosoft.webscrappertest.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "cu.neosoft.webscrappertest.MainActivity" on path: DexPathList[[zip file "/data/app/cu.neosoft.webscrappertest-hy3VhMUfmFw2eV1pLwg5LQ==/base.apk"],nativeLibraryDirectories=[/data/app/cu.neosoft.webscrappertest-hy3VhMUfmFw2eV1pLwg5LQ==/lib/arm64, /system/lib64, /vendor/lib64, /system/product/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3195)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "cu.neosoft.webscrappertest.MainActivity" on path: DexPathList[[zip file "/data/app/cu.neosoft.webscrappertest-hy3VhMUfmFw2eV1pLwg5LQ==/base.apk"],nativeLibraryDirectories=[/data/app/cu.neosoft.webscrappertest-hy3VhMUfmFw2eV1pLwg5LQ==/lib/arm64, /system/lib64, /vendor/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3183)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7397) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/cu.neosoft.webscrappertest-hy3VhMUfmFw2eV1pLwg5LQ==/base.apk because: Bad encoded_array value: Failure to verify dex file '/data/app/cu.neosoft.webscrappertest-hy3VhMUfmFw2eV1pLwg5LQ==/base.apk': Bad encoded_value method type size 7
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:365)
        at dalvik.system.DexFile.<init>(DexFile.java:107)
        at dalvik.system.DexFile.<init>(DexFile.java:80)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:444)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:403)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:126)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:101)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:74)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:87)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:116)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:114)
        at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:60)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:851)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:950)
        at android.app.LoadedApk.getResources(LoadedApk.java:1188)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2462)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2454)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6353)
2020-05-19 01:26:31.400 14644-14644/? E/AndroidRuntime:     at android.app.ActivityThread.access$1300(ActivityThread.java:220)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
        		... 6 more
```

If there is any need for more info I'll be happy to provide it.
Thanks in advance !

**Comment by christian-draeger** [comment] 2020-05-20 10:10
Can not reproduce, do you have an example project that I can clone?

**Comment by masterwok** [comment] 2020-05-21 00:58
@christian-draeger I'm also running into issues when trying to import kscrape. The issue is occurring in this demo application:

[https://github.com/masterwok/borked-skrape](https://github.com/masterwok/borked-skrape)

![errors](https://user-images.githubusercontent.com/5054978/82511928-92869e80-9adc-11ea-929b-fa2e71ab2af0.png)

>Android Studio 3.6.3
Build #AI-192.7142.36.36.6392135, built on April 13, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.6.10-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: IdeaVIM, com.thvardhan.gradianto, com.vincentp.gruvbox-theme, io.github.xiaopihai7256, izhangzhihao.rainbow.brackets, com.google.services.firebase

**Comment by masterwok** [comment] 2020-05-21 01:08
Seems like first issue can only be resolved by removing methods with spaces in them (like this [one](https://github.com/skrapeit/skrape.it/blob/736496e2705081259689f947b4b11d6620aa7442/src/main/kotlin/it/skrape/matchers/Matchers.kt#L21)) or by having a min SDK version of 26 and above (not realistic).

**Comment by GrayTsar** [comment] 2020-07-12 23:59
I build the library with gradle myself and added it into a android studio project. Added the library into a android studio project. The error seems gone but now I get.
`java.lang.NoClassDefFoundError: Failed resolution of: Lio/github/rybalkinsd/kohttp/client/ClientBuilderImplKt;`

with 

`            val a = skrape {
                url = "https://www.google.com/"

                extract {
                    statusCode
                }
            }`

**Comment by christian-draeger** [comment] 2020-08-23 17:59
i just kicked all functions that contains spaces in its names in commit ecbec25908c6ad2851e75c9fd3fd5bc946a39e86
since i'am not into android development, could someone please verify if it helped to avoid the errors regarding dex?

the version including the change is available via jitpack:

```kotlin
repositories {
    jcenter()
    maven {
        url = uri("https://jitpack.io")
    }
}

implementation("com.github.skrapeit:skrape.it: ecbec25908")
`
``

if it hopefully helped i will release it to maven central as well

**Comment by christian-draeger** [comment] 2020-08-23 18:28
if one could help or have an idea to continuously check the android compatibility (maybe during CI build with github actions, or using some linting as part of the gradle build or have an example android project that uses skrape{it}s latest master) it is highly appreciated.
ideas, hints or even better PRs are highly welcome

**Comment by noloman** [comment] 2020-08-28 11:08
> i just kicked all functions that contains spaces in its names in commit [ecbec25](https://github.com/skrapeit/skrape.it/commit/ecbec25908c6ad2851e75c9fd3fd5bc946a39e86)
> since i'am not into android development, could someone please verify if it helped to avoid the errors regarding dex?
> 
> the version including the change is available via jitpack:
> 
> ```kotlin
> repositories {
>     jcenter()
>     maven {
>         url = uri("https://jitpack.io")
>     }
> }
> 
> implementation("com.github.skrapeit:skrape.it:ecbec25908")
> ```
> 
> if it hopefully helped i will release it to maven central as well

thanks a lot, I will try to test it this weekend!

**Comment by noloman** [comment] 2020-08-28 11:09
> if one could help or have an idea to continuously check the android compatibility (maybe during CI build with github actions, or using some linting as part of the gradle build or have an example android project that uses skrape{it}s latest master) it is highly appreciated.
> ideas, hints or even better PRs are highly welcome

I'm going to use skrape{it} in an Android project, so I can keep you guys updated 😄

**Comment by noloman** [comment] 2020-09-01 12:28
> i just kicked all functions that contains spaces in its names in commit [ecbec25](https://github.com/skrapeit/skrape.it/commit/ecbec25908c6ad2851e75c9fd3fd5bc946a39e86)
> since i'am not into android development, could someone please verify if it helped to avoid the errors regarding dex?
> 
> the version including the change is available via jitpack:
> 
> ```kotlin
> repositories {
>     jcenter()
>     maven {
>         url = uri("https://jitpack.io")
>     }
> }
> 
> implementation("com.github.skrapeit:skrape.it:ecbec25908")
> ```
> 
> if it hopefully helped i will release it to maven central as well

hi hi!
I've tested this in a debug version of my app and it seems to be working! thanks a lot!

**Comment by noloman** [comment] 2020-09-01 14:24
By the way, I just realized while looking at https://developer.android.com/studio/write/java8-support that, if using Android, enabling `minifyEnabled` in the `build.gradle` of the `app` mobile works, although it takes way longer for the build to be generated. This might be an OK workaround for other developers with the same problem.

**Comment by christian-draeger** [comment] 2020-09-02 10:56
could it be possible that you have to configure proguard by the use of the proguard.cfg file like it is explained here:
https://www.guardsquare.com/en/products/proguard/manual/examples

since i haven't worked with proguard or android personally i can not say much about the values that have to be set there. maybe someone with more android expertise can help on the proguard topic?

**Comment by noloman** [comment] 2020-09-02 12:07
> could it be possible that you have to configure proguard by the use of the proguard.cfg file like it is explained here:
> [guardsquare.com/en/products/proguard/manual/examples](https://www.guardsquare.com/en/products/proguard/manual/examples)
> 
> since i haven't worked with proguard or android personally i can not say much about the values that have to be set there. maybe someone with more android expertise can help on the proguard topic?

Indeed I'm afraid we're going to need some help with this because I really have no idea.
Would it be possible to maybe refactor some parts of the app not to use the _fancy methods_ that Android can't make use of? Or maybe create alternative methods that the Android app can use? 
Anyways if there's somebody with more advance knowledge, welcome, because I'm not sure I can do more

**Comment by faogustavo** [comment] 2020-10-07 16:05
@noloman have you tried to force the kotlin to compile to jvm8?

```gradle
android {

  // ...

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

  kotlinOptions {
    jvmTarget = "1.8"
  }

  // ...
}
```

**Comment by christian-draeger** [comment] 2020-10-09 21:47
Thx to @faogustavo and we have a working android example over here:
https://github.com/skrapeit/skrape-android-sample

**Closed** 2020-10-14 08:05 UTC
Labels: bug, help wanted
