### ISSUE TITLE
[BUG] The current Kotlin Version is defined as 1.4.10 but the KotlinCompile task is still using 1.3

### ISSUE THREAD

**Issue by faogustavo** [skrapeit/skrape.it#118] opened 2020-10-07 10:24 UTC
This is not actually a bug, but the compile task is with the wrong kotlin version

![image](https://user-images.githubusercontent.com/7588480/95319173-ef0d0f00-086d-11eb-8424-f0a4a5dd27ad.png)

![image](https://user-images.githubusercontent.com/7588480/95319198-f46a5980-086d-11eb-8225-98858f20f577.png)

**Comment by christian-draeger** [comment] 2020-10-07 12:39
i think we need this to support android if i remember correct, there has been some issue. with the current settings we are able to work with 1.4 features in our code but compile everything down to 1.3
so i guess i wont fix it until android issue is clarified

**Comment by faogustavo** [comment] 2020-10-07 12:46
@christian-draeger can you link here the issue? 
I'm an android developer and all my projects are already using Kotlin 1.4.10 and they are working OK

**Comment by christian-draeger** [comment] 2020-10-07 15:10
ah it was with the java version (see my last commit). after that change one confirmed it is working.
https://github.com/skrapeit/skrape.it/issues/93

but in general this issue #93 is unclear to me since i am not into android development and don't know how to fix or verify if there is really an issue. help to clarify #93 is highly welcome 

i will merge your PR regarding kotlin 1.4

**Closed** 2020-10-07 15:10 UTC
Labels: bug
